
initial_cells = [
    # Blinker
    #[1, 1],
    #[1, 2],
    #[1, 3],
    
    # Block
    #[4, 4],
    #[4, 5],
    #[5, 4],
    #[5, 5],
    
    # Beehive
    #[7, 8],
    #[7, 9],
    #[8, 7],
    #[8, 10],
    #[9, 8],
    #[9, 9],
    
    # Gleiter
    #[1, 2],
    #[2, 3],
    #[3, 1],
    #[3, 2],
    #[3, 3]
    
    # Spaceship
    [1, 1],
    [1, 4],
    [2, 5],
    [3, 1],
    [3, 5],
    [4, 2],
    [4, 3],
    [4, 4],
    [4, 5]
]

[grid_size]
width = 30
height = 30